### ISSUE TITLE
This mod crashes Minecraft on startup.

### ISSUE THREAD

**Issue by websitebuilder1000** [kwpugh/ring_of_teleport_fabric-1.17#1]
I installed this Fabric mod for Java 1.17, and when I tried to launch Minecraft,, it crashed due to some error with this mod. Here's the full crash report:
`---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 11/21/21, 1:52 PM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ring_of_teleport'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:457)
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/serializer/PartitioningSerializer$GlobalData
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:149)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at com.kwpugh.ring_of_teleport.RingOfTeleport.<clinit>(RingOfTeleport.java:17)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:466)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.serializer.PartitioningSerializer$GlobalData
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:636)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	... 25 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:457)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 425838208 bytes (406 MiB) / 1174405120 bytes (1120 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD A12-9800 RADEON R7, 12 COMPUTE CORES 4C+8G 
	Identifier: AuthenticAMD Family 21 Model 101 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon R7 Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x9874
	Graphics card #0 versionInfo: DriverVersion=21.19.524.768
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 14525.25
	Virtual memory used (MB): 6821.55
	Swap memory total (MB): 2810.20
	Swap memory used (MB): 205.07
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.42.1+1.17
		fabric-api-base: Fabric API Base 0.4.0+5847535018
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+5847535018
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.2+5847535018
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+5847535018
		fabric-command-api-v1: Fabric Command API (v1) 1.1.4+5847535018
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+5847535018
		fabric-containers-v0: Fabric Containers (v0) 0.1.13+5847535018
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.1+5847535018
		fabric-copper-golem: Copper Golem 1.0.1+1.17.1
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.6+5847535018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.13+5847535018
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.1+5847535018
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.11+5847535018
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+5847535018
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.8+5847535018
		fabric-item-api-v1: Fabric Item API (v1) 1.2.5+5847535018
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+5847535018
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+5847535018
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.3+5847535018
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.5+5847535018
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.5+5847535018
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 1.0.2+6d0fac4218
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.5+6d0fac4218
		fabric-models-v0: Fabric Models (v0) 0.3.1+5847535018
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.14+5847535018
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.12+5847535018
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+5847535018
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.11+6d0fac4218
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.5+6d0fac4218
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+5847535018
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.13+5847535018
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+5847535018
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.9+5847535018
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.6+6d0fac4218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+5847535018
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.2.1+6d0fac4218
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.7+6d0fac4218
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.1+6d0fac4218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.9+5847535018
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.5+5847535018
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.9+5847535018
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.14+5847535018
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.2+5847535018
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+5847535018
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.3.1+eb76084f18
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.1+6d0fac4218
		fabricloader: Fabric Loader 0.12.5
		java: OpenJDK 64-Bit Server VM 16
		minecraft: Minecraft 1.17.1
		ring_of_teleport: Ring Of Teleport 1.0.6
	Launched Version: fabric-loader-0.12.5-1.17.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>`

**Comment by kwpugh** [comment]
Looks like you are missing the required Cloth Config API

![Screen Shot 2021-11-21 at 1 58 09 PM](https://user-images.githubusercontent.com/8809210/142776982-5a170845-20d1-4e54-bdfb-15ba716decc2.png)

**Comment by websitebuilder1000** [comment]
Thanks! Closing thread.
